export const CHALLONGE_API_URL: string = "https://api.challonge.com/v1/";

export const CHALLONGE_PARAMS: { [key: string]: any } = {
    TOURNAMENT: {
        CREATE: {
            API_KEY: "api_key",
            NAME: "name",
            TOURNAMENT_TYPE: "tournament_type",
            URL: "url",
            SUBDOMAIN: "subdomain",
            DESCRIPTION: "description",
            OPEN_SIGNUP: "open_signup",
            HOLD_THIRD_PLACE_MATCH: "hold_third_place_match",
            PTS_FOR_MATCH_WIN: "pts_for_match_win",
            PTS_FOR_MATCH_TIE: "pts_for_match_tie",
            PTS_FOR_GAME_WIN: "pts_for_game_win",
            PTS_FOR_GAME_TIE: "pts_for_game_tie",
            PTS_FOR_BYE: "pts_for_bye",
            SWISS_ROUNDS: "swiss_rounds",
            RANKED_BY: "ranked_by",
            RR_PTS_FOR_MATCH_WIN: "rr_pts_for_match_win",
            RR_PTS_FOR_MATCH_TIE: "rr_pts_for_match_tie",
            RR_PTS_FOR_GAME_WIN: "rr_pts_for_game_win",
            RR_PTS_FOR_GAME_TIE: "rr_pts_for_game_tie",
            ACCEPT_ATTACHMENTS: "accept_attachments",
            HIDE_FORUM: "hide_forum",
            SHOW_ROUNDS: "show_rounds",
            PRIVATE: "private",
            NOTIFY_USERS_WHEN_MATCHES_OPEN: "notify_users_when_matches_open",
            NOTIFY_USERS_WHEN_THE_TOURNAMENT_ENDS: "notify_users_when_the_tournament_ends",
            SEQUENTIAL_PAIRINGS: "sequential_pairings",
            SIGNUP_CAP: "signup_cap",
            START_AT: "start_at",
            CHECK_IN_DURATION: "check_in_duration",
            GRAND_FINALS_MODIFIER: "grand_finals_modifier",
        },
    },
    PARTICIPANT: {
        CREATE: {
            API_KEY: "api_key",
            TOURNAMENT: "tournament",
            NAME: "name",
            CHALLONGE_USERNAME: "challonge_username",
            EMAIL: "email",
            SEED: "seed",
            MISC: "misc",
        },
    },
};
